VAGRANTSERVICEHOME = "/home/admred/Proyecto/vagrant/"
VAGRANTSLAVE1="127.0.0.1"
SLAVE1PORT="8000"
FILELOG="file.log"
MSGlog="message.log"
BDProyectos="BDProyectos.json"
BDSlave="BDSlave.json"
MSGSlave="msgSlave.json"
